### ISSUE TITLE
Design a System for Polyfills

### ISSUE THREAD

**Issue by ktemkin** [reilabs/llvm-to-cairo#25]
## Description

Conventionally, LLVM handles mismatches between platform capabilities by using the `compiler-rt` library. This provides the basic level of platform support expected by LLVM IR. This effort will effectively require an implementation of this functionality, but the exact form of this support library is to be determined. 

The primary task here is to determine how we want to make these polyfills _available_ to the compiled code (#24), and also how the polyfills should be structured in a uniform fashion. It also needs to work out how we plan to compile the polyfills into the same (`FlatLowered`?) representation as the compiled LLVM IR. 

We want to make the system heavily modular so that new polyfills can be added without having to change the polyfill system or the way the polyfills are emitted.

**Comment by iamrecursion** [comment]
Based on observations and discussions between @ktemkin and myself, it is apparent that we actually need to solve linkage properly even at this early stage. We have decided, in brief to:

- Create our own IR based on `FlatLowered` for our `.flo` object files. We call this the `FlatLowered` Intermediate Representation or `FLIR`. It will start as a copy of `FlatLowered` and then evolve as we need it, and will be able to round-trip with `FlatLowered`. There _may_ be potential to contribute this back in future, depending on how different it ends up.
- The compiler works on single object files only, ingesting `.ll` files and outputting `.flo` files with a 1:1 mapping.
- A separate linker takes `.flo` files that came out of the LLVM compiler or out of Cairo itself and performs linking.

The linking process can be summarized as follows.

1. We go through them and build a symbol table, which we may decide to embed in the object files at a later date.
2. We then iterate through each object, find things with linkage that is *NOT* internal. If not premangled we mangle the name
3. We emit all code into a new `MultiFlatLowered` (this is _actual_ `FlatLowered` for ingestion by `sierragen`, not `FLIR`) object replacing any non-internal linkage references with concretized references.
4. We do one final consistency check to ensure we have replaced all references with internal linkage.

At this point things can be passed onwards to `sierragen` for generation of Sierra and CASM.
